### ISSUE TITLE
Very good experiment!

### ISSUE THREAD

**Issue by ice1000** [dwjackson/EditSomeXML#1]
This xml editor is awesome.
And I'm building a game engine on jvm, looking for a xml visualizer.

Can I integrate this editor into my engine tools? (I'll tell the original author's information.
:+1: Thx!

**Comment by dwjackson** [comment]
The project is licensed under the MPL so as long as you distribute your changes to the files that you modify under the same license you can integrate it into whatever you're building.

**Comment by ice1000** [comment]
Got it. :+1:
